#!/usr/bin/env python
###################################################################################
#TextListener
#Takes a picture of a page of printed text, performs Optical Character Recognition (OCR) 
#on the image and save as text file then the file is synthesised by Text To Speech (TTS) reads it aloud.
#
#
#31 Oct,2016
#
#Rashid Mahmud
###################################################################################
import RPi.GPIO as GPIO
from time import sleep
from subprocess import call
import re
import os
#Setup pin
GPIO.setmode(GPIO.BCM)

#GPIO.setup(17, GPIO.OUT)
GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)

os.system('espeak -v+f3 "Press button to initiate."')

#Function splits a big paragraph into smaller sentences for easy TTS
def splitParagraphIntoSentences(paragraph):
    sentenceEnders = re.compile('[.!?]')
    sentenceList = sentenceEnders.split(paragraph)
    return sentenceList

#Calls the Espeak TTS Engine to read aloud a sentence
#	-ven+m7:	Male voice
#	-s180:		set reading to 180 Words per minute
#	-k20:		Emphasis on Capital letters
def sound(spk):
    cmd_beg=" espeak -ven+m7 -s160 -k20 --stdout '"
    cmd_end="' | aplay"
    print (cmd_beg+spk+cmd_end)
    call ([cmd_beg+spk+cmd_end], shell=True)


while True:
    input_state = GPIO.input(18)
    if input_state == False:
        
        GPIO.output(17, GPIO.HIGH)
        sleep(2)
        GPIO.output(17, GPIO.LOW)
		#Turn on flash light while taking picture
		
        os.system('espeak -v+f3 "Taking image."')
        print('Taking Image')
        #Take an image from the RaspberryPi camera with sharpness 100 and shutter speed 2s(increases the readability of the text for OCR)
        call ("raspistill -rot 90 -o j2.jpg -t 2000 -sh 100", shell=True)
        print ('Image taken')
        
        #Start the Tesseract OCR and save the text to out1.txt
        os.system('espeak -v+f3 "Processing, please wait, It may take a few minutes."')
        call ("tesseract j2.jpg out1", shell=True)
        print ('OCR complete')
        
        #Open the text file and split the paragraph to Sentences
        fname="out1.txt"
        f=open(fname)
        content=f.read()
        print (content)
        sentences = splitParagraphIntoSentences(content)
        
        #Speak aloud each sentence in the paragraph one by one
        for s in sentences:
            sound(s.strip())
